### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by ylboerner** [gematik/ISiK-Medikation#92]
- [x] SUSHI Version erhöhen
- [ ] Validierungsfehler prüfen
- [x] Use slice name instead of numeric index access
- [x] Fix eventual errors
```[tasklist]
### Tasks
- [x] PTDATA-674
```
